<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Sandata.Tools.AudioPool</RootNamespace>
    <AssemblyName>Sandata.Tools.AudioPool</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" />
  </ItemGroup>

</Project>
