<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AutonomousArena.Core/AutonomousArena.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Content.Builder.Task" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" />
  </ItemGroup>
  <ItemGroup>
    <MonoGameContentReference Include="Content/Content.mgcb" />
  </ItemGroup>
</Project>
