<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Hukbo.Core/Hukbo.Core.csproj" />
    <ProjectReference Include="../Hukbo.Diagnostics/Hukbo.Diagnostics.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Hukbo.Core.Tests" />
  </ItemGroup>
</Project>
