using Sandata.Core.Maps;
using Sandata.Core.Navigation;

namespace Sandata.Core.Tests;

/// <summary>
/// Plan task 18's done-when: "<c>NavBakeTests</c> passes against a
/// hand-computed 8 by 8 fixture asserted cell by cell, including an
/// axis-parallel wall, a 26.57-degree wall, a closed door, and the inflation
/// boundary at exactly one body radius."
///
/// <para>
/// The fixture's expected grid below was derived independently of
/// <see cref="NavBake"/>'s implementation — by hand, cell by cell, from the
/// three records' own geometry and a Chebyshev-distance inflation rule — and
/// only then compared against what <see cref="NavBake.Bake"/> produces. It
/// was never generated by running the implementation and pasted back.
/// </para>
/// </summary>
public sealed class NavBakeTests
{
    // The 8x8 fixture (32x32 wu on a 4 wu cell, body radius 5 wu, so
    // inflateCells == ceil(5 / 4) == 2 whole cells, Chebyshev distance).
    //
    // Records:
    //   WALL 28 0 28 4 1   -- axis-parallel (vertical), cells (7,0),(7,1)
    //   WALL 0 20 8 24 1   -- run (+8,+4): atan(4/8) == 26.57 degrees, the
    //                         same angle as the angle-house fixture's
    //                         WALL 120 120 320 220 (design section 12),
    //                         scaled down. Supercover cells, hand-walked:
    //                         (0,5),(1,5),(2,5),(2,6).
    //   DOOR 16 0 16 4 0 0 -- closed (State 0), cells (4,0),(4,1). Kept
    //                         Door: nearest wall-source (7,1) is Chebyshev
    //                         distance max(3,1)=3, one cell past the
    //                         radius-2 inflation boundary.
    //
    // Inflation (radius 2, Chebyshev, sourced only from the wall cells
    // above -- a closed door is never an inflation source):
    //   Wall 1's two cells (7,0)/(7,1) inflate to the rectangle
    //   rows 0-3 x cols 5-7.
    //   Wall 2's four cells inflate to the rectangle rows 3-7 x cols 0-4
    //   (every one of the four cells' own radius-2 square, unioned, works
    //   out to exactly that rectangle -- verified column range per row by
    //   hand in the design notes for this task).
    //   The two rectangles are disjoint (column gap at col 4 vs col 5) and
    //   neither reaches the door cells at (4,0)/(4,1), which stay Door.
    //
    // Row 3 is the one row both rectangles reach at once (wall 1's rows
    // 0-3, wall 2's rows 3-7), so it comes out fully blocked end to end --
    // an arithmetic coincidence of the two chosen wall positions, not a
    // rule, and confirmed independently column by column above.
    //
    // '.' = Open, '#' = Blocked, 'D' = Door (closed, still passable to the
    // planner at high cost).
    private static readonly string[] ExpectedGrid =
    [
        ". . . . D # # #", // row 0
        ". . . . D # # #", // row 1
        ". . . . . # # #", // row 2
        "# # # # # # # #", // row 3
        "# # # # # . . .", // row 4
        "# # # # # . . .", // row 5
        "# # # # # . . .", // row 6
        "# # # # # . . .", // row 7
    ];

    private static readonly WallRecord AxisParallelWall =
        new(LineNumber: 1, X1: 28, Y1: 0, X2: 28, Y2: 4, Material: 1);

    private static readonly WallRecord DiagonalWall =
        new(LineNumber: 2, X1: 0, Y1: 20, X2: 8, Y2: 24, Material: 1);

    private static readonly DoorRecord ClosedDoor =
        new(LineNumber: 3, X1: 16, Y1: 0, X2: 16, Y2: 4, Hinge: 0, State: 0);

    private static NavGrid BakeFixture()
    {
        var grid = new NavGrid(width: 8, height: 8);

        NavBake.Bake(
            grid,
            walls: [AxisParallelWall, DiagonalWall],
            doors: [ClosedDoor],
            bodyRadiusWu: 5);

        return grid;
    }

    private static NavCellFlags FlagFor(char symbol) => symbol switch
    {
        '.' => NavCellFlags.Open,
        '#' => NavCellFlags.Blocked,
        'D' => NavCellFlags.Door,
        _ => throw new ArgumentOutOfRangeException(nameof(symbol), symbol, "Fixture symbol must be '.', '#', or 'D'."),
    };

    [Fact]
    public void Bake_MatchesTheHandComputedEightByEightFixture_CellByCell()
    {
        var grid = BakeFixture();

        for (var y = 0; y < ExpectedGrid.Length; y++)
        {
            var rowSymbols = ExpectedGrid[y].Split(' ');
            Assert.Equal(grid.Width, rowSymbols.Length);

            for (var x = 0; x < rowSymbols.Length; x++)
            {
                var expected = FlagFor(rowSymbols[x][0]);
                var actual = grid.Passability[grid.CellIndex(x, y)];

                Assert.True(
                    expected == actual,
                    $"Cell ({x}, {y}): expected {expected} but was {actual}.");
            }
        }
    }

    // The doorway-narrowing behaviour design section 7 describes: a wall's
    // inflation reaches exactly two cells (body radius 5 wu / cell size 4 wu,
    // rounded up), so the cell at Chebyshev distance 2 from wall source
    // (2, 5) is forced Blocked and the cell at distance 3 is left Open.
    [Theory]
    [InlineData(4, 5, NavCellFlags.Blocked)] // distance 2 from (2, 5): inside the radius
    [InlineData(5, 5, NavCellFlags.Open)] // distance 3 from (2, 5): one cell past the radius
    public void Bake_InflationBoundaryFallsExactlyAtTheBodyRadius(int x, int y, NavCellFlags expected)
    {
        var grid = BakeFixture();

        Assert.Equal(expected, grid.Passability[grid.CellIndex(x, y)]);
    }

    [Fact]
    public void Bake_ClosedDoorCellsStayDoor_NotBlockedAndNotPlainOpen()
    {
        var grid = BakeFixture();

        Assert.Equal(NavCellFlags.Door, grid.Passability[grid.CellIndex(4, 0)]);
        Assert.Equal(NavCellFlags.Door, grid.Passability[grid.CellIndex(4, 1)]);
    }

    [Fact]
    public void Bake_SkipsAnOpenDoor_LeavingItsCellsAtWhateverInflationWouldOtherwiseGive()
    {
        var grid = new NavGrid(width: 8, height: 8);
        var openDoor = new DoorRecord(LineNumber: 1, X1: 24, Y1: 16, X2: 24, Y2: 20, Hinge: 0, State: 1);

        // Isolated from any wall (there are none in this fixture), so an
        // open door's cells must simply be Open -- never Door, since State
        // 1 means NavBake.Bake never rasterizes it at all.
        NavBake.Bake(grid, walls: [], doors: [openDoor], bodyRadiusWu: 5);

        Assert.Equal(NavCellFlags.Open, grid.Passability[grid.CellIndex(6, 4)]);
        Assert.Equal(NavCellFlags.Open, grid.Passability[grid.CellIndex(6, 5)]);
    }

    [Fact]
    public void Bake_IsIdempotent_RepeatedCallsOnTheSameGridProduceTheSameResult()
    {
        var grid = BakeFixture();
        var firstBake = (NavCellFlags[])grid.Passability.Clone();

        NavBake.Bake(
            grid,
            walls: [AxisParallelWall, DiagonalWall],
            doors: [ClosedDoor],
            bodyRadiusWu: 5);

        Assert.Equal(firstBake, grid.Passability);
    }

    [Fact]
    public void Bake_ThrowsArgumentNullException_ForANullGrid()
    {
        Assert.Throws<ArgumentNullException>(
            () => NavBake.Bake(null!, walls: [], doors: [], bodyRadiusWu: 5));
    }

    [Fact]
    public void Bake_ThrowsArgumentNullException_ForNullWalls()
    {
        var grid = new NavGrid(width: 4, height: 4);

        Assert.Throws<ArgumentNullException>(
            () => NavBake.Bake(grid, walls: null!, doors: [], bodyRadiusWu: 5));
    }

    [Fact]
    public void Bake_ThrowsArgumentNullException_ForNullDoors()
    {
        var grid = new NavGrid(width: 4, height: 4);

        Assert.Throws<ArgumentNullException>(
            () => NavBake.Bake(grid, walls: [], doors: null!, bodyRadiusWu: 5));
    }

    [Theory]
    [InlineData(0)]
    [InlineData(-1)]
    public void Bake_ThrowsArgumentOutOfRangeException_ForANonPositiveBodyRadius(int bodyRadiusWu)
    {
        var grid = new NavGrid(width: 4, height: 4);

        Assert.Throws<ArgumentOutOfRangeException>(
            () => NavBake.Bake(grid, walls: [], doors: [], bodyRadiusWu));
    }

    [Fact]
    public void Bake_ADegenerateWallInsideOneCell_BlocksOnlyThatCell()
    {
        var grid = new NavGrid(width: 4, height: 4);
        // Both endpoints land in cell (1, 1): x in [4, 8), y in [4, 8).
        var wall = new WallRecord(LineNumber: 1, X1: 5, Y1: 5, X2: 7, Y2: 6, Material: 0);

        // A body radius of 1 wu keeps inflateCells at
        // ceil(1 / 4) == 1, so the check below stays about rasterization,
        // not inflation swallowing every other assertion.
        NavBake.Bake(grid, walls: [wall], doors: [], bodyRadiusWu: 1);

        Assert.Equal(NavCellFlags.Blocked, grid.Passability[grid.CellIndex(1, 1)]);
        Assert.Equal(NavCellFlags.Open, grid.Passability[grid.CellIndex(3, 3)]); // Chebyshev distance 2, past radius 1
    }
}
